activities:
  work-item-to-pdf:
    output: output
    activityRoot: .
    environment:
      path:
        - bin
      pythonPath:
        - variables
        - libraries
        - resources
    action:
      command:
        - python
        - -m
        - robot
        - -d
        - output
        - --logtitle
        - Task log
        - ./tasks/*.robot
condaConfig: config/conda.yaml
