activities:
  work-item-to-pdf:
    output: output
    activityRoot: .
    environment:
      pythonPath:
        - variables
    action:
      command:
        - python
        - -m
        - robot
        - --report
        - NONE
        - --outputdir
        - output
        - --logtitle
        - Task log
        - tasks.robot
condaConfig: conda.yaml
