activities:
  Web store orders:
    output: output
    activityRoot: .
    environment:
      path:
        - bin
      pythonPath:
        - libraries
    action:
      command:
        - python
        - -m
        - robot
        - --report
        - NONE
        - --outputdir
        - output
        - --logtitle
        - Task log
        - tasks.robot
condaConfig: conda.yaml
