activities:
  RobotSpareBin Starter:
    output: output
    activityRoot: .
    action:
      command:
        - python
        - -m
        - robot
        - -d
        - output
        - --logtitle
        - Task log
        - ./tasks/*.robot
condaConfig: config/conda.yaml
