activities:
  Image search:
    output: output
    activityRoot: .
    environment:
      path:
        - .
      pythonPath:
        - .
    action:
      command:
        - python
        - -m
        - robot
        - --report
        - NONE
        - -d
        - output
        - --logtitle
        - Task log
        - tasks.robot

condaConfig: conda.yaml
ignoreFiles:
    - .gitignore
